= Палеонтология
:imagesdir: images
:icons: font
:sectanchors:
:sectlinks:

// Хлебные крошки
https://mgri-university.github.io/reggeo/index.html[🏠 Главная] / Палеонтология

'''

== О дисциплине

Палеонтоло́гия (от др.-греч. παλαιοντολογία) — наука о жизни, существовавшей до начала голоценовой эпохи или в её начале (примерно 11 700 лет назад) в прошлые геологические периоды. Она включает в себя изучение фоссилий (ископаемых остатков) для определения эволюции организмов и их взаимодействия с окружающей средой (палеоэкология). Палеонтологические наблюдения были задокументированы ещё в V веке до н. э. Палеонтология как наука была создана в XVIII веке в результате работ Жоржа Кювье по сравнительной анатомии и быстро развивалась в XIX веке. Сам термин происходит от др.-греч. παλαιός [palaios] — «древний», ὄν [on] — «существо, тварь» и λόγος [logos] — «слово, понятие».

'''

== Учебные материалы по курсу Палеонтологии

[%autowidth, cols="2,3,^1", options="header"]
|===
|Тип данных |Название |Файл

|Учебник (ресурс Geokniga.org)
|Бондаренко О.Б., Михайлова И.А. Палеонтология. Издательство МГУ, Москва, 2006
|http://www.geokniga.org/books/10226[Скачать]

|Учебник (ресурс Казанский федеральный университет)
|Е.Е. Сухов. Палеонтология. Краткий курс лекций. 2013
|https://dspace.kpfu.ru/xmlui/bitstream/handle/net/21340/03_018_kl-000348.pdf[Скачать]

|Лекция / Презентация
|Лекция «Эволюция организмов по данным палеонтологии». Комаров В.Н.
|https://youtu.be/XDYtbgq0q-0[Смотреть]

|===

'''

https://mgri-university.github.io/reggeo/index.html[← На главную страницу]

'''

_Почта для связи:_ samohvalovsa@mgri.ru
