name: github pages

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        uses: docker://asciidoctor/docker-asciidoctor@sha256:56fd995a52c5b997c70cbcba49d93cb7f70a911e69c1cf7029e8135dc11e5292
        with:
          args: 'sh -c "asciidoctor *.adoc && ls -la"'

      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
          # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
