name: Build and publish MGRI community site
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: build asciidoctor files
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: mgred/asciidoctor-action@master
        with:
          args: asciidoctor *.adoc -D pubilc
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
